### ISSUE TITLE
Sharing codebase

### ISSUE THREAD

**Issue by enchantinggg4** [waldo-vision/waldo.desktop.app#9]
I'm not sure whether desktop application would differ from web version, but If it is like discord app(enhanced web app), there need to be a some way of sharing codebase. Submodule shared by web and desktop applications is a decent solution

**Comment by Steveplays28** [comment]
Basically everything's gonna be different so there's no point in sharing the code base lol.

Website is gonna have:
- landing page
- about
- download

Desktop app is gonna have:
- video conversion/home page, with some stats probably and graphs
- about
- settings

So there's no point really.
